name: Deploy to AWS Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # - run: docker build -t boltgun69/docker-react-demo -f Dockerfile.dev .
      # - run: docker run -e CI=true boltgun69/docker-react-demo npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-demo-gh
          environment_name: docker-react-demo-gh-env
          existing_bucket_name: elasticbeanstalk-us-west-1-815332568426
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
